[package]
name = "metatablesnow/typography"
description = "A simple way to manage RichText"
license = "MIT"
authors = ["metatablesnow"]
version = "0.1.1"

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]
